server:
  port: 8083

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:paymentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

razorpay:
  key-id: rzp_test_SxQq74CtwDVnCJ
  key-secret: 7TJcNlF5D4JtgysOkaRo5KkC

services:
  rental-service-url: https://wattever-1.onrender.com
  station-service-url: https://wattever-2.onrender.com

logging:
  level:
    com.waterx: DEBUG
