server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
              - "https://wattever.vercel.app"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: station-service
          uri: https://wattever-2.onrender.com
          predicates:
            - Path=/api/stations/**
        - id: rental-service
          uri: https://wattever-1.onrender.com
          predicates:
            - Path=/api/rentals/**
        - id: payment-service
          uri: https://wattever-3.onrender.com
          predicates:
            - Path=/api/payments/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
